import { sql } from '../../db.js';
import { placeStackDown } from '../../canvas-layout.js';
import { generateDesignMd } from '../../design-md.js';

/**
 * Extract a reusable design artifact from a site node into a new
 * `designmd` node. The snapshot stores BOTH representations:
 *   - design_md — a genuine DESIGN.md spec generated by an LLM pass
 *     over the site's HTML (lib/design-md.js). This is what run-flow's
 *     md bucket injects as "DESIGN.MD SOURCE" (COMPOSE_SYSTEM restyle).
 *   - html — the source site's full HTML, kept as the chassis template
 *     that applyDesign()/Demarcelizer reskin consumes.
 *
 * Conceptually: extractDesign answers "save this site's look so I can
 * apply it elsewhere". The result is a separate node the user can
 * iterate on (rename, refine), and then plug into multiple targets.
 */
export const extractDesignTool = {
  name: 'extractDesign',
  description: 'Distill a site\'s visual language into a separate "design system" node. Generates a real DESIGN.md spec (colors, typography, layout, components) from the site\'s HTML and also keeps the HTML as a style template — so the node works both as a design.md source on the canvas (connect + run) and via applyDesign. Use this when the user says things like "save this style", "extract this design", "I want to reuse this look".',
  // Confirm chips are reserved for deletes (2026-06-12). Extraction only
  // CREATES a node — nothing to protect.
  classification: 'safe',
  inputSchema: {
    type: 'object',
    properties: {
      siteNodeId: { type: 'string', description: 'Id of the site node whose current snapshot should be saved as a design template.' },
      name:       { type: 'string', description: 'Optional display name for the new design node. Defaults to the source site\'s name + " — design".' },
    },
    required: ['siteNodeId'],
  },

  async execute(args, ctx) {
    const { siteNodeId, name = null } = args || {};
    if (!siteNodeId) return { error: 'invalid_args', message: 'siteNodeId required' };

    const rows = await sql`
      SELECT n.id, n.kind, n.meta, n.current_snapshot_id, s.html
      FROM nodes n
      LEFT JOIN snapshots s ON s.id = n.current_snapshot_id
      JOIN boards b ON b.id = n.board_id
      WHERE n.id = ${siteNodeId} AND b.id = ${ctx.boardId} AND b.user_id = ${ctx.userId}
    `;
    if (!rows.length) return { error: 'target_not_found', message: 'siteNodeId not found' };
    const src = rows[0];
    if (src.kind !== 'site') return { error: 'invalid_args', message: 'extractDesign expects a site node' };
    if (!src.current_snapshot_id || !src.html) return { error: 'no_snapshot', message: 'site has no current snapshot to extract' };

    // Distill the design system BEFORE touching the DB — an LLM failure
    // must not leave an empty designmd node behind.
    let designMd, mdTruncated;
    try {
      const gen = await generateDesignMd({ html: src.html });
      designMd = gen.md;
      mdTruncated = gen.truncated;
    } catch (e) {
      return { error: 'extract_failed', message: String(e?.message || e) };
    }

    const sourceName = src.meta?.name || 'site';
    const displayName = name || `${sourceName} — design`;
    const width = 480;
    const height = 320;
    const { x: posX, y: posY } = await placeStackDown(ctx.boardId, width, height, sql);
    const meta = { name: displayName, source: 'agent-extracted', sourceSiteNodeId: siteNodeId };
    if (mdTruncated) meta.extractTruncated = true;

    const [node] = await sql`
      INSERT INTO nodes (board_id, kind, pos_x, pos_y, width, height, meta)
      VALUES (${ctx.boardId}, 'designmd', ${posX}, ${posY}, ${width}, ${height}, ${JSON.stringify(meta)}::jsonb)
      RETURNING id
    `;
    const [snap] = await sql`
      INSERT INTO snapshots (node_id, html, design_md, source)
      VALUES (${node.id}, ${src.html}, ${designMd}, 'extract')
      RETURNING id
    `;
    await sql`UPDATE nodes SET current_snapshot_id = ${snap.id} WHERE id = ${node.id}`;

    // Wire the source site → design node so the chain is visible.
    try {
      await sql`
        INSERT INTO edges (board_id, source_node_id, target_node_id, kind)
        VALUES (${ctx.boardId}, ${siteNodeId}, ${node.id}, 'generic')
      `;
    } catch (_) { /* dup edge — ignore */ }

    if (ctx?.emit) {
      try { ctx.emit('graph_mutated', { reason: 'extractDesign:done' }); } catch (_) {}
    }
    const result = {
      extracted: true,
      designNodeId: node.id,
      sourceSiteNodeId: siteNodeId,
      name: displayName,
    };
    // Surface truncation so the agent tells the user instead of the cap
    // failing silently ("the page was very large; the design spec was
    // distilled from the first part of the document").
    if (mdTruncated) {
      result.warning = 'source_truncated';
      result.warningDetail = 'The site HTML exceeded the extraction size limit; the design spec was distilled from the beginning of the document (where the styling lives). Mention this to the user.';
    }
    return result;
  },
};
